<a href="https://colab.research.google.com/github/Madushani-Weerasekara/NLP2_SelfStudy/blob/main/NLP2_SelfStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [159]:
pip install nltk


In [160]:
# import librarie
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [161]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [162]:
paragraph = """Osho" redirects here. For other uses, see Rajneesh (disambiguation) and Osho (disambiguation).
Bhagwan Shree Rajneesh
Rajneesh c. 1977
Born	Chandra Mohan Jain

11 December 1931
Kuchwada, Bhopal State, British India
Died	19 January 1990 (aged 58)
Pune, Maharashtra, India
Nationality	Indian
Education	Dr. Hari Singh Gour University (MA)
Known for	Spirituality, mysticism, anti-religion[1]
Movement	Neo-sannyasins[1]
Memorial(s)	Osho International Meditation Resort, Pune
Website	osho.com

Rajneesh (born Chandra Mohan Jain; 11 December 1931 – 19 January 1990), also known as Acharya Rajneesh,[2] Bhagwan Shree Rajneesh,[1] and later as Osho (Hindi pronunciation: [ˈo:ʃo:]), was an Indian Godman,[3] philosopher, mystic, and founder of the Rajneesh movement.[1] He was viewed as a controversial new religious movement leader during his life. He rejected institutional religions,[4][1][5] insisting that spiritual experience could not be organized into any one system of religious dogma.[6] As a guru, he advocated meditation and taught a unique form called dynamic meditation. Rejecting traditional ascetic practices, he advocated that his followers live fully in the world but without attachment to it.[6] In expressing a more progressive attitude to sexuality[7] he caused controversy in India during the late 1960s and became known as "the sex guru".[1][8][9] """

In [163]:
# Tokenization
# cnvert paragraph into sentences
sentences = nltk.sent_tokenize(paragraph)
print(sentences)



['Osho" redirects here.', 'For other uses, see Rajneesh (disambiguation) and Osho (disambiguation).', 'Bhagwan Shree Rajneesh\nRajneesh c. 1977\nBorn\tChandra Mohan Jain\n\n11 December 1931\nKuchwada, Bhopal State, British India\nDied\t19 January 1990 (aged 58)\nPune, Maharashtra, India\nNationality\tIndian\nEducation\tDr. Hari Singh Gour University (MA)\nKnown for\tSpirituality, mysticism, anti-religion[1]\nMovement\tNeo-sannyasins[1]\nMemorial(s)\tOsho International Meditation Resort, Pune\nWebsite\tosho.com\n\nRajneesh (born Chandra Mohan Jain; 11 December 1931 – 19 January 1990), also known as Acharya Rajneesh,[2] Bhagwan Shree Rajneesh,[1] and later as Osho (Hindi pronunciation: [ˈo:ʃo:]), was an Indian Godman,[3] philosopher, mystic, and founder of the Rajneesh movement.', '[1] He was viewed as a controversial new religious movement leader during his life.', 'He rejected institutional religions,[4][1][5] insisting that spiritual experience could not be organized into any one syst

In [164]:
len(sentences)

9

In [165]:
# Split sentences into words
for sentence in sentences:
  words = nltk.word_tokenize(sentence)
  print(words)

['Osho', "''", 'redirects', 'here', '.']
['For', 'other', 'uses', ',', 'see', 'Rajneesh', '(', 'disambiguation', ')', 'and', 'Osho', '(', 'disambiguation', ')', '.']
['Bhagwan', 'Shree', 'Rajneesh', 'Rajneesh', 'c.', '1977', 'Born', 'Chandra', 'Mohan', 'Jain', '11', 'December', '1931', 'Kuchwada', ',', 'Bhopal', 'State', ',', 'British', 'India', 'Died', '19', 'January', '1990', '(', 'aged', '58', ')', 'Pune', ',', 'Maharashtra', ',', 'India', 'Nationality', 'Indian', 'Education', 'Dr.', 'Hari', 'Singh', 'Gour', 'University', '(', 'MA', ')', 'Known', 'for', 'Spirituality', ',', 'mysticism', ',', 'anti-religion', '[', '1', ']', 'Movement', 'Neo-sannyasins', '[', '1', ']', 'Memorial', '(', 's', ')', 'Osho', 'International', 'Meditation', 'Resort', ',', 'Pune', 'Website', 'osho.com', 'Rajneesh', '(', 'born', 'Chandra', 'Mohan', 'Jain', ';', '11', 'December', '1931', '–', '19', 'January', '1990', ')', ',', 'also', 'known', 'as', 'Acharya', 'Rajneesh', ',', '[', '2', ']', 'Bhagwan', 'Shree',

In [166]:
# clean the text using re
import re
for i in range(len(sentences)):
  stop_words = set (stopwords.words('english'))
  cleaned_text = re.sub('[^a-zA-Z]', " ", sentences[i])
  cleaned_text = cleaned_text.lower()
  cleaned_text = cleaned_text.split()
  cleaned_text = [word for word in cleaned_text if word not in stop_words]
  print(cleaned_text)




['osho', 'redirects']
['uses', 'see', 'rajneesh', 'disambiguation', 'osho', 'disambiguation']
['bhagwan', 'shree', 'rajneesh', 'rajneesh', 'c', 'born', 'chandra', 'mohan', 'jain', 'december', 'kuchwada', 'bhopal', 'state', 'british', 'india', 'died', 'january', 'aged', 'pune', 'maharashtra', 'india', 'nationality', 'indian', 'education', 'dr', 'hari', 'singh', 'gour', 'university', 'known', 'spirituality', 'mysticism', 'anti', 'religion', 'movement', 'neo', 'sannyasins', 'memorial', 'osho', 'international', 'meditation', 'resort', 'pune', 'website', 'osho', 'com', 'rajneesh', 'born', 'chandra', 'mohan', 'jain', 'december', 'january', 'also', 'known', 'acharya', 'rajneesh', 'bhagwan', 'shree', 'rajneesh', 'later', 'osho', 'hindi', 'pronunciation', 'indian', 'godman', 'philosopher', 'mystic', 'founder', 'rajneesh', 'movement']
['viewed', 'controversial', 'new', 'religious', 'movement', 'leader', 'life']
['rejected', 'institutional', 'religions', 'insisting', 'spiritual', 'experience', 'c

In [167]:
len(sentences)

9

In [168]:
#apply stemming

stemmer = PorterStemmer()

for i in range(len(sentences)):

  for word in words:
    if word not in set(stopwords.words('english')):
      stemmed_words = stemmer.stem(word)
      print(stemmed_words)

[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]


In [169]:
# Apply lemmatization

lemmatizer = WordNetLemmatizer()

for i in range(len(sentences)):
  for word in words:
    if word not in set(stopwords.words('english')):
      lemmatized_word = lemmatizer.lemmatize(word)
      print(lemmatized_word)

[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]
[
1
]
[
8
]
[
9
]


In [170]:
#Apply BOW
# CountVectorizer --> Convert a collection of text documents to a matrix of token counts.
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True, ngram_range = (2,3),max_features = 10)



In [171]:
x = cv.fit_transform(sentences)


In [172]:
print(x.toarray())

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [1 0 1 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [173]:
x[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [174]:
cv.vocabulary_

{'osho disambiguation': 8,
 '11 december': 0,
 'osho com': 6,
 'known as': 2,
 'osho hindi': 9,
 'osho com rajneesh': 7,
 'organized into': 4,
 'organized into any': 5,
 'one system of': 3,
 'he advocated': 1}

In [175]:
# Apply TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
x = cv.fit_transform(sentences)


In [176]:
sentences[6]

'Rejecting traditional ascetic practices, he advocated that his followers live fully in the world but without attachment to it.'

In [177]:
x[0]

<1x129 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [178]:
x[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.62754252, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [179]:
print(x.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.16792106 0.16792106 0.16792106 ... 0.         0.08396053 0.08396053]
 ...
 [0.         0.         0.         ... 0.2466213  0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [180]:
cv.vocabulary_

{'osho': 89,
 'redirects': 97,
 'here': 53,
 'for': 44,
 'other': 90,
 'uses': 121,
 'see': 105,
 'rajneesh': 96,
 'disambiguation': 35,
 'and': 12,
 'bhagwan': 21,
 'shree': 108,
 '1977': 4,
 'born': 23,
 'chandra': 28,
 'mohan': 77,
 'jain': 64,
 '11': 0,
 'december': 33,
 '1931': 2,
 'kuchwada': 67,
 'bhopal': 22,
 'state': 112,
 'british': 24,
 'india': 57,
 'died': 34,
 '19': 1,
 'january': 65,
 '1990': 5,
 'aged': 9,
 '58': 6,
 'pune': 95,
 'maharashtra': 74,
 'nationality': 82,
 'indian': 58,
 'education': 40,
 'dr': 37,
 'hari': 51,
 'singh': 109,
 'gour': 49,
 'university': 120,
 'ma': 73,
 'known': 66,
 'spirituality': 111,
 'mysticism': 81,
 'anti': 13,
 'religion': 100,
 'movement': 79,
 'neo': 83,
 'sannyasins': 104,
 'memorial': 76,
 'international': 61,
 'meditation': 75,
 'resort': 103,
 'website': 124,
 'com': 29,
 'also': 10,
 'as': 15,
 'acharya': 7,
 'later': 69,
 'hindi': 54,
 'pronunciation': 94,
 'ˈo': 128,
 'ʃo': 127,
 'was': 123,
 'an': 11,
 'godman': 48,
 'phi